Date::DATE_FORMATS[:default] = '%d %b %Y'
Time::DATE_FORMATS[:default] = '%d %b %Y at %I:%M %p'
Date::DATE_FORMATS[:viewer] = '%B %Y'
Date::DATE_FORMATS[:short] = '%d %b %y'
Date::DATE_FORMATS[:long] = '%d %b %Y'
